name: Enforce Merge Restrictions

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest

      - name: Check if PR branch is allowed
        if: github.base_ref == 'main'
        run: |
          if [[ ! ${GITHUB_HEAD_REF} =~ ^release/ ]]; then
            echo "Branch ${GITHUB_HEAD_REF} is not allowed to merge into main."
            exit 1
          fi
