name: Enforce Merge Restrictions

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      allowed: ${{ steps.check.outputs.allowed }}
    steps:
      - name: Check if PR branch is allowed
        id: check
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^release/ ]]; then
            echo "Branch ${{ github.head_ref }} is not allowed to merge into main."
            echo "allowed=false" >> $GITHUB_ENV
            exit 1
          else
            echo "allowed=true" >> $GITHUB_ENV
          fi

  test:
    needs: check-branch
    runs-on: ubuntu-latest
    if: needs.check-branch.outputs.allowed == 'true'
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest
