name: Enforce Merge Restrictions

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR branch is allowed
        if: github.base_ref == 'main'
        run: |
          if [[ ! ${GITHUB_HEAD_REF} =~ ^release/ ]]; then
            echo "Branch ${GITHUB_HEAD_REF} is not allowed to merge into main."
            exit 1
          fi

