name: Enforce Merge Restrictions

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      allowed: ${{ steps.check.outputs.allowed }}
    steps:
      - name: Check if PR branch is allowed
        id: check
        run: |
          if [[ "${{ github.base_ref }}" == "main" && ! "${{ github.head_ref }}" =~ ^release/ ]]; then
            echo "Branch ${{ github.head_ref }} is not allowed to merge into main."
            echo "::set-output name=allowed::false"
            exit 1
          else
            echo "::set-output name=allowed::true"
          fi
